### ISSUE TITLE
can you give more details about the training, all the three models

### ISSUE THREAD

**Issue by flynightair** [SpeakerGuard/SpeakerGuard#1]
how to generate the .ckpt file in x-vector
i only get final.raw by x-vector in kadli

**Comment by SpeakerGuard** [comment]
Hello, in our repo, for xvector:
```
ckpt (extractor_file): it is derived from https://github.com/manojpamk/pytorch_xvectors
plda_file, tranform_mat_file, and mean_file: they are derived from kaldi, but were converted to text format using the command 'ivector-copy-plda' and 'mat-copy' of kaldi.
```

**Comment by SpeakerGuard** [comment]
AS you suggest, we will provide more detail about the models.

**Comment by flynightair** [comment]
> 
thanks, i will try again later

**Comment by SpeakerGuard** [comment]
You can train audionet by natural_train.py or adver_train.py, depending on your purpose.

**Comment by flynightair** [comment]
> You can train audionet by natural_train.py or adver_train.py, depending on your purpose.

Thanks very much

**Comment by flynightair** [comment]
> Hello, in our repo, for xvector:
> 
> ```
> ckpt (extractor_file): it is derived from https://github.com/manojpamk/pytorch_xvectors
> plda_file, tranform_mat_file, and mean_file: they are derived from kaldi, but were converted to text format using the command 'ivector-copy-plda' and 'mat-copy' of kaldi.
> ```

hi, can you upload the x-vector training code in the article and detail the corresponding processes
the model from 'https://github.com/manojpamk/pytorch_xvectors' is different from the given ones in the pre-trained-models. The structure in pytorch_xvectors is  "xx: {'step': xx, 'exp_avg': tensor([ .......])", but in the pre-trained-models xvecTDNN_origin.ckpt is "('bn_fc2.num_batches_tracked', tensor(xxx)), ('fc3.weight', tensor([[...]]) , ('fc3.bias', tensor([...])"

**Comment by SpeakerGuard** [comment]
hello, the pre-trained model provided by 'https://github.com/manojpamk/pytorch_xvectors' is a dict and contains useless information about the traning detail. You should extract the 'model_state_dict' from the dict, which is exactly the xvecTDNN_origin.ckpt in our repo.

**Comment by SpeakerGuard** [comment]
![image](https://user-images.githubusercontent.com/101247320/180597081-a2ac2b7f-0569-4df5-b25d-0fc17c78ae55.png)

**Comment by flynightair** [comment]
ok, i get. Thanks.

**Comment by naem9u** [comment]
Hello, I would like to convert plda_file to a text format file.
Can you explain briefly the "ivector-copy-plda" command?

Thx!
