### ISSUE TITLE
Re-inference of the adversarial sample get different attack accuracy

### ISSUE THREAD

**Issue by WWWWWLI** [SpeakerGuard/SpeakerGuard#3]
Using the PGD method to attack the model, the generated samples are saved and the success rate of the attack is Acc1. However, I re-entered the generated samples into the model and tested the success rate of the attack as Acc2. theoretically Acc1 should be the same as Acc2, but I obtained different results, i.e. Acc1 is not equal to Acc2. Have you done any relevant tests or encountered the same problem? I re-tested with the model in eval mode and this is OK, how do you think I should debug?

**Comment by SpeakerGuard** [comment]
Hi, how large is the gap between Acc1 and Acc2? A small gap is reasonable given the precision error of the computation.

**Comment by SpeakerGuard** [comment]
Also, make sure you have set the model in eval mode when you craft adversarial voices for them.

**Comment by SpeakerGuard** [comment]
The model should be set in the eval mode for both generating and testing adversarial voices.
